export const ServicesData=[
  {
    slug:"hairfall",
    title:"Hairfall and its remedy",
    subtitle:"We diagnose the root cause of hair fall and offer customized treatments to restore healthy hair growth",
    img:"/Medical-Services/hair-fall-&-remedy.jpg",
    spantext:"It Starts",
    headline:"Hairfall and its remedy",
    link:"HT surgery ie. FUE (Follicular Unit Extraction)",
    para1:"Today hairfall is the most common issue affecting all ages right from ages of 5 years till old age. Every one has different reasons for their hairfall which usually starts as a sudden onset and can linger on for many months and years leading to significant loss of volume of hair and tinning on top of head.",
    para2:"The most common reason for hairfall tends to be lifestyle induced stress. This stress can be physical due to long hectic hours of work or study, arising from late nights and lack of good quality sleep. To add to this, are poor eating habits like avoiding certain nutritious foods or eating at wrong times which can make one deficient in essential micronutrients required for good hair growth. Late nights cause an upset of digestive systems that cause poor absorption of nutrients from our diet, despite eating a “healthy nutritious” diet. Coupled with physical stress, is the mental stress that takes its toll on sleep and mood. This also restricts many normal physiological processes that affect our haircycle length leading to excess hairfall.",
    para3:"To add to the stress of hairfall is the presence of dandruff that makes the scalp very greasy and hair becomes dry and frizzy. Managing such hair tresses is very difficult and frustrating. Dandruff is sign of weakness of immune system that starts to fail under the effect of stress. This dandruff is an overgrowth of fungus, Pityrosporum ovale, which is present on the scalp of every human being and is supposed to protect us from other more infectious bacteria and fungi.",
    para4:"Juvenis Clinic specializes in identifying the root cause of hairfall for each patient and tailor make treatments that will stop hairfall within 2 months and then regrow hair within the next 4 months. Emphasis is laid more on lifestyle modifications as they will help a lot in treatment outcomes. A mix of oral medications (antifungals, hair vitamins, etc) and applications that help in stopping hairfall and grow hair are given along with the right kind of shampoo and conditioner for the hair type.",
    para5:"Dr Nilesh Goyal also specializes in Nanofat/ SVF injections for hair regrowth. This is modified fat that is rich in stem cells and growth factors that helps in regrowing hair in most types of alopecia. This is proven to be far superior to PRP which has only growth factors.",
    para6:"Genetic cause of alopecia results in patterned hair loss in males and females. It is caused by the effect of DiHydroTestosterone (DHT) on the hair cycle length and its diameter. This eventually causes roots to disappear leading to balding. Treatment is aimed to cut off the effect of DHT on hair roots in the form of DHT blockers ( 5 alpha reductase inihibitors) like Finasteride and Dutasteride along with application of Minoxidil. Hair Transplant Surgery is considered when there are gaps that are not filled with medical therapy. Juvenis clinic follows the latest technique for HT surgery ie. FUE (Follicular Unit Extraction)",
    para6half:"method of acquiring grafts and implantation with two forceps method.",
   } ,
   {
    slug:"Psoriasis",
    title:"Psoriasis Treatment",
    subtitle:"Psoriasis is an inflammatory skin condition affecting upto 2% of the worlds population. It has a strong association with stress and hence, is associated with many systemic lifestyle illnesses like diabetes, hypertension and heart disease.",
    img:"/Medical-Services/psoriasis-treatment.jpg",
    spantext:"It Starts",
    headline:"Psoriasis Treatment",
    para1:"Psoriasis is an inflammatory skin condition affecting upto 2% of the worlds population. It has a strong association with stress and hence, is associated with many systemic lifestyle illnesses like diabetes, hypertension and heart disease.",
    para2:"It has been proven to be a genetic disease. So, in essence, patients of psoriasis have a gene that leads to start of the disease. It is difficult to predict the time of onset. It has been found to occur in infancy and can also present first time at the far end of life. The association with stressful lifestyle is very strong. There has been a slow increase in psoriasis in India over the last few decades. This could be due to increasing unhealthy lifestyle choices by persons all age groups.",
    para3:"Due to its genetic causation, it is impossible to cure one of psoriasis. However, huge research by pharma companies in the western world has now got us multiple highly effective treatment options that can make a person disease free.",
    para4:"Current treatment modalities include cream applications, oral tablets and injectable biologics that have together helped in achieving near 100% PASI reduction. Treatment intensity is directly proportional to disease severity and patient health. Also some of the latest drugs are very expensive which leads to cost benefit evaluation while deciding treatment plan.",
    para5:"Dr Nilesh Goyal has worked in many skin centres across the NHS UK where he has managed many psoriasis patients of all ages and with severe forms of disease. He has been part of Psoriasis clinic at Hope Hospital, Manchester UK which caters to the most severely affected by psoriasis.",
    para6:"Come to Juvenis Clinic to get your psoriasis managed as per international standards with latest medications. Treatment plans are tailored to suit your lifestyle and budgets.",
   } ,
   {
    slug:"filler",
    title:"",
    subtitle:"The art of fat filling is like a sculptor working on a stone statue and giving it the perfect shape step by step. The guidance is not to overfill as fat cells would not survive if there were too many in a small area.",
    img:"/Surgical-Services/filler.jpg",
    halftitle:"Filler in city for an antiaging effect",
    spantext:"Fat the best",
    headline:"Fat the best filler in city for an antiaging effect",
    para1:"Fat as a Filler? Shocking and even disgusting to some. Putting fat into your face suddenly brings in images of bloated face and an immediate NO!! from my patients. But when they see the results of others who have undergone this same procedure, they immediately agree to get it done.",
    para2:"The idea of fat as a filler originated about 130 years ago when modern day fillers were not invented. It was primarily thought of as a volume restoring agent filled under scars of tuberculosis which was rampant in Germany at the time. Many other agents were also tried at the time including animal fat and paraffin wax but all these led to tragic outcomes. An individuals own fat worked and survived the best when inserted under depressed areas. But then the acquiring of fat became an issue as fat had to be cut out from some other area of body resulting in a new scar. The procedure fell into disrepute till Liposuction got invented in the mid 1970s in Europe. Liposuction gave access to a huge quantity of fat which was usually thrown away after the procedure. But Prof Pierre Fournier, an aesthetic surgeon from Paris, realized that this fat could be injected on the face to restore volume. He would also go to the lengths of asking patients to rub the fat into their face every night to get a glow. Long after, the advancement in medical science revealed the superior quality of fat as a grafting material. It was found to have an abundance of Mesenchymal Stem Cells now called as Adipose Derived Stem Cells (ADSCs). Along with these messiahs of repair, are a whole host of growth factors which help in regenerating tissues where this fat is placed.",
    para3:"Fat grafting is a surgical procedure that needs sterile instruments and a clean sterile operating theatre. Patient must be healthy with well controlled parameters of blood sugar and blood pressure. The filling of fat is ideally measured with injection of saline to calculate the exact amount in each segment of face. There is no set formula for filling as it is done for hyaluronic acid (HA) fillers done commonly in dermatology clinics across the world. This helps in enhancing the features specific to the person. It contrasts with the clone like appearance of all those who get HA fillers done.",
    para5:"The art of fat filling is like a sculptor working on a stone statue and giving it the perfect shape step by step. The guidance is not to overfill as fat cells would not survive if there were too many in a small area. It is generally understood that around half of the injected fat gets resorbed by the body. But the remaining half survives for life giving a filling effect. The stem cells and growth factors also placed along with adipocytes help in regenerating the aging tissues and fresh texture to skin. The glow thus acquired is unmatchable with any known current skin rejuvenating technology like Lasers/ RF tightening/ microneedling/ PRP or stem cells injections. This glow lasts for years compared with that from all the other procedures.",
    images: [
      "/Juvenis-images-compress/Fat filling 38ml in young female.jpg",
      "/Juvenis-images-compress/Fat filling of face 35mls in young man.jpg",
      "/Juvenis-images-compress/Fat filling of face 40mls front view.jpg",
      "/Juvenis-images-compress/Fat filling of face 40mls left side view.jpg",
      "/Juvenis-images-compress/Fat filling of face 40mls right side view.jpg",
      "/Juvenis-images-compress/Fat filling under eyes.jpg",
      "/Juvenis-images-compress/Full face fat filling 40mls.jpg",
     
    ]
   },
   {
    slug:"Hairtransplant",
    title:"Your Journey to",
    halftitle:"Starts Here.",
    subtitle:"We offer safe and effective hair transplant solutions to help you regain hair density and boost your confidence.",
    img:"/Surgical-Services/hair-transplant.jpg",
    spantext:"Fuller Hair",
    headline:"Hair Transplant Surgery",
    para1:"Hair transplant surgery is a vital cog in the correction of hair thinning and loss of volume. It was envisaged in the 1950s and 60s when the concept of male pattern hair loss was identified by Norman Orentriech. The idea that hair follicles continue to retain their characteristics even when they are transplanted to a different area is the basis for hair transplant surgery.",
    para2:"The procedure has undergone many changes since its invention. From strips of scalp being placed in the recipient areas to now single follicular unit grafts, it has changed dramatically giving near natural appearance to patients world over. The change in techniques with modern instruments have led to faster and more quicker surgeries with larger areas covered in one sitting.",
    para3:"Juvenis Clinic follows the latest in Hair transplant Surgery techniques. It specializes in doctor led Follicular Unit Extraction (FUE) and two forceps implantation technique that is the norm over the last 15 years. The procedure is done by Dr Nilesh Goyal who was trained in this surgery by Dr Robert Jones of Toronto, Canada. He has a team of well trained HT Technicians and Nurses who assist in the procedure. All members of the team have their role defined leading to a smooth flow throughout the procedure.",
    para4:"FUE technique has taken away the pain and bleeding that used to be the norm with strip method of hair transplants. Apart from a mild heaviness of the head, there is no pain after the procedure. A small strip of tight bandage is placed on forehead to prevent swelling of eyes after the surgery. Patient comfort is given utmost importance during the entire procedure which can last upto 12 hours. Dr Nilesh Goyal specializes in giving scalp nerve blocks that reduce the sensations over the entire scalp. Dr Jeffrey Klein’s (California, USA) technique of Tumescent Local Anaesthesia is employed for the donor and recipient areas. This makes the procedure very safe and comfortable for patients.",
    para5:"A detailed post procedure instruction sheet is given to patients who are taught the technique of washing grafted area without touching them. A regime of antibiotics and hair growth stimulants are to be followed to get the desired results.",
    para6:"The grafts get settled in the new location within 2 weeks and then start to grow in 2 months after the surgery. Complete growth takes around 6 to 8 months. Patients are called twice tin the first month after surgery and then are seen 2 monthly to check on their progress.",
    para7:"Current market trends are such that patients are lured to hair transplant clinics with the promise of very cheap rates. Do not fall prey to such gimmicks. These clinics are not manned by proper doctors and to top it, the procedure is done by technicians only whose training and level of expertise cannot be ascertained. The doctors at such clinics are not trained in hair transplant surgeries. There are also many studios that offer hair transplant surgery. Beware of these as there is no doctor in these places.",
    para7:"Dr Goyal has corrected many failed hair transplant surgeries done at such dubious centres.",
    images: [
      "/Juvenis-images-compress/Frontal hairline restored with FUE HT.jpg",
      "/Juvenis-images-compress/FUE HT 1200 grafts to fronatl area.jpg",
      "/Juvenis-images-compress/FUE HT for Female pattern hair loss.jpg",
      "/Juvenis-images-compress/Grade 3 MPHL FUE HT 9 months.jpg",
      "/Juvenis-images-compress/Hair regrowth medications only in 43 yr old at 10 months.jpg",
      "/Juvenis-images-compress/Hair regrowth within 2 months in 64 yr old diabetic (1).jpg",
      "/Juvenis-images-compress/HT new frontal hairline.jpg",
      "/Juvenis-images-compress/HT young man 6 months.jpg",
     
    ]
   },
   {
    slug:"vitiligo-treatment",
    title:"Vitiligo Treatment",
    halftitle:"",
    subtitle:"Vitiligo, also known as the dreaded White patch disease, Leukoderma or Kode in local language, is an autoimmune disease that can occur at any age and in all human beings across the globe.",
    img:"/Medical-Services/vitiligo-treatment.jpg",
    spantext:"Start Here",
    headline:"Vitiligo Treatment",
    para1:"Vitiligo, also known as the dreaded White patch disease, Leukoderma or Kode in local language, is an autoimmune disease that can occur at any age and in all human beings across the globe. It does not spare even famous celebrities. Michael Jackson was afflicted by it for which he depigmented himself completely when a large part of his skin turned white. ",
    para2:"In India, the white patches are mistaken for Leprosy which is a bacterial infection of the skin causing lighter patches with no sensations. There is a huge social stigma attached to leprosy as it is a communicable disease resulting in severe deformities of hands and feet. With modern day access to treatment, deformities in leprosy have reduced significantly. However, the social stigma refuses to die down. ",
    para3:"Vitiligo presents as a depigmented white patch on any part of the body. It has no preceding symptoms of redness or itching. It spreads slowly with increasing size of patches and occasionally newer ones coming at sites of injury. Exacerbations of disease can often be times with other serious illnesses and periods of stress.",
    para4:"Vitiligo can also occur only in one half of the body when it is called segmental vitiligo. This variant spreads rapidly and then stops after a few months. It is difficult to treat this with medications only but it responds very well to surgical methods.The other variant is Lip Tip variety. Here patches are present on lips and tips of fingers. These areas show very poor response to medications which are used mainly for stabilizing the disease. Stable vitiligo is that which has shown new patches or extension of old patches for a period of 6 months at least",
    para5:"The common variant is the Non Segmental vitiligo that presents with patches in any part of the body and spreads slowly. It responds well to medications, however, these must be continued for long to achieve complete repigmentation. In some patients, the disease keeps recurring despite treatment.",
    para6:"",
    para7:"",
    para7:"",
     images: [
      "/Juvenis-images-compress/Vitiligo repigmentation FUE pubic hair.jpg",

]
   },
    {
    slug:"acne-treatment",
    title:"Acne Treatment",
    halftitle:"",
    subtitle:"Acne commonly known as pimples or zits are common in teenage years but can often present into late twenties or early thirties when they become a huge nuisance.",
    img:"/Medical-Services/acne-treatment.jpg",
    spantext:"",
    headline:"Acne Treatment",
    para1:"Acne commonly known as pimples or zits are common in teenage years but can often present into late twenties or early thirties when they become a huge nuisance.",
    para2:"The common presentations are that of red bumps which turn into yellow heads (pustules) that rupture leaving raw areas on face. In severe cases, there can be deep seated nodules that heal with scars. Scars remain for life though they often get better as time passes. To treat acne early is to prevent scars that are permanent.",
    para3:"Treatment of acne depends upon the stage and age of patient. Early in the disease, treatments are mainly geared towards killing the bacteria responsible for infection of the enlarged sebaceous glands in the skin. Later, there are treatments that improve function of sebaceous glands by unblocking them and regulating sebum production. Isotretinoin is the only drug that works on this pathway and hence makes a big difference in the outcome. But a full course of isotretinoin lasting few months can leave a person with dry lips, nose, eyes and skin. The benefits of such treatment far outweigh the side effects. An oily complexion in hot humid summers of Mumbai will start loving their skin when on isotretinoin.",
    para4:"Isotretinoin does have scar modifying effect too on acne scars. They look much reduced when the course is on. But after finishing the course these scars return to normal skin colour. Such scars can be treated with modern dermatosurgical methods like Subcision using Nokor needle, Fractional co2 laser resurfacing, Fat grafting including nanofat injections, scar excision, punch excision, etc. In extreme scarring full skin dermabrasion has been done by Dr Goyal with very good cosmetic results.",
    para5:"Adult Acne needs a mention here. These are acne that occur after the age of 25 years. The primary characteristic of such acne is that they present as red pimples that stay for very long, do not convert to yellow head and often heal with a pigmented scar. They are always secondary to hormonal upset because of stressful  lifestyle measures.",
    para6:"",
    para7:"",
    para8:"",

   },
   {
    
    slug:"vitiligo-surgery",
    title:"Vitiligo Surgery",
    halftitle:"",
    subtitle:"Vitiligo, also known as the dreaded White patch disease, Leukoderma or Kode in local language, is an autoimmune disease that can occur at any age and in all human beings across the globe.",
    img:"/Surgical-Services/vitiligo-surgery.jpg",
    spantext:"",
    headline:"Vitiligo Surgery",
    para1:"India is at the forefront of vitiligo surgery with conceptualizing the ideas and showing them to work in various types of vitiligo. There are more than 5 types of vitiligo surgery that are routinely done to achieve repigmentation. These are Non cultured Epidermal Cell Suspension done by putting a mixture of epidermal cells (most superficial layer of skin) onto the white patches. Then there is Jodhpur technique which uses a mixture of epidermal cells by dermabrading the skin surrounding the patches or from a different site and places them onto the white patches. Follicular Unit Hair Grafting into the patches is also a very successful type of surgery for repigmentation. Dr Nilesh Goyal specializes in transplanting pubic hair onto the vitiligo patch and achieving repigmentation. The older surgical methods like suction blister grafting, ultra-thin skin grafting and mini punch grafting are also done in specific situations. ",
    para2:" ",
    para3:"",
    para4:"",
    para5:"",
    para6:"",
    para7:"",
    para7:"",

   },
   {
    
    slug:"eczema",
    title:"Eczema",
    halftitle:"",
    subtitle:"Eczema is a broad term encompassing various forms of skin conditions that has become red, itchy and can ooze.",
    img:"/Medical-Services/Eczema.jpg",
    spantext:"",
    headline:"Eczema",
    para1:"Atopic Dermatitis: Often hereditary, this is the most common form of eczema. It typically presents as itchy, inflamed skin and is frequently associated with asthma or hay fever. Presents often in Infancy and can have a tumultuous progression throughout life. This tends to have an effect on the physical growth of child and their educational performance. Treatments can include immunosuppressant medications like Steroids, Cyclosporine, Azathioprine and latest biological drugs. ",
    para2:"Contact Dermatitis: Caused by skin's reaction to irritants or allergens, this type leads to localized redness and inflammation where the substance came into contact.",
    para3:"Dyshidrotic Eczema(aka Pompholyx): This form affects the hands and feet, causing small, itchy blisters. It’s often triggered by stress, allergens, or exposure to certain metals.",
    para4:"Nummular Eczema: This variety manifests as coin-shaped patches of irritated skin, commonly caused by dry skin or environmental changes.",
    para5:"Seborrheic Dermatitis: Often linked to oil-producing areas like the scalp and face, this form leads to flaky patches and redness. It starts due to overgrowth of a fungus, Malassezia species on scalp which is the result of poor immune response secondary to stressful lifestyle.",
    para6:"Stasis Dermatitis: (aka Gravitational eczema) Related to poor circulation in the lower legs, it can cause swollen, itchy skin and discoloration around ankles progressing upwards when not treated. Often this can lead to cellulitis needing hospital admission for IV antibiotics.",
    treat1:"Managing eczema requires a tailored approach based on the type and severity. Common treatments include:",
    treat2:"Moisturizers: They are the most important part of treatment of eczema. Regular use of emollients can help lock in moisture, reducing dryness and irritation. The choice of moisturizer as per skin type and season is very important for achieving optimal benefit.",
    treat3:"Topical Corticosteroids: These are prescribed to reduce inflammation and itching during flare-ups. Dr Nilesh Goyal prescribes them in 5 day cyclical pattern reducing their side effects and at the same time getting maximum benefit.",
    treat4:"Antihistamines: Often used to manage itching, particularly at night.",
    treat5:"Topical Calcineurin Inhibitors: Non-steroidal creams like tacrolimus or pimecrolimus help control inflammation in sensitive areas. They help in reducing dependency on steroid creams.",
    treat6:"Light Therapy: Phototherapy using UV light may be recommended for persistent or severe eczema.",
    treat7:"Systemic Medications: In severe cases, oral medications like steroid, cyclosporine or azathioprine and latest entrant, tofacitinib are employed. When these are found ineffective then Dr Goyal resorts to injectable drugs like biologics (e.g., dupilumab) to manage the disease.",
    treat8:"Trigger Avoidance: Identifying and avoiding triggers like allergens, irritants, or stress is crucial for long-term management. Adopting healthy lifestyle choices helps a lot in halting disease progression and frequent flareups. These include wearing soft cotton fabrics, regular skin care routine, eating and sleeping at natural times.",
    treatheadline:"Treatments for Eczema"

   },
   {
    
    slug:"Liposuction",
    title:"Liposuction",
    halftitle:"",
    subtitle:"Liposuction is the removal of excess fat under the skin from areas that are difficult to lose by diet and exercise.",
    img:"/Surgical-Services/Liposuction-and-Body-Sculpting.jpg",
    spantext:"",
    para7link:"Tumescent Anaesthesia Liposuction (ISTAL)",
    para8link:"Liposculptors Dermatologic Forum (LDF)",
    headline:"Liposuction",
    para1:"Liposuction is the removal of excess fat under the skin from areas that are difficult to lose by diet and exercise. Rather fat which returns when diet and exercise slacken. Before we start to label fat as our enemy that stops us from looking attractive, we need to understand that fat or adipose tissue is the only reason we look beautiful. This layer of fat cells under our skin forms a smooth padding over the muscles and bones of our body. It has many functions in addition to giving us a shape. Fat is necessary for managing the heat loss from our body. It has many stem cells and growth factors that help in regeneration of our tissue when we are unwell. So naturally we have fat depots that are genetically determined which come into action in times of crisis. This gives rise to body curves that are unique to families, races and leads to cultural identities. Beauty is defined as per race, color and geographic locations. Hence this must be different for people from differing races.",
    para2:"Excess fat deposits that occur due to lifestyle and genetics often become target of ridicule for the individual. They are thought to be sign of unhealthiness and laziness. Even when the person diets and exercises, these fat deposits only reduce in size to a certain extent. To add to this, the reduction is not permanent. Fat cells shrink when one loses weight following diet and exercise and better lifestyle. However, they grow back and fill up with yellow fat as soon as the person slows on diet and exercise. On top of this, diet and exercise can be a huge torture to the entire body and mind. It takes a heavy toll on the psyche of the individual. This tendency makes it frustrating for many individuals to go for better lifestyle measures.",
    para3:"Liposuction helps in permanently losing the fat cells from under the skin. The bulging areas can be flattened within no time. Fat cells once lost can take a very long time to regrow. Often the areas treated never fill up again. This procedure has no bearing on diet and exercise. The individual can continue to eat and drink normally and exercise regularly to maintain their shape. ",
    para4:"There is lot of bad press about liposuction in the media. It is true, that a huge number of patients have lost their lives during or immediately after undergoing liposuction. But these occur when liposuction is done under general anaesthesia. This technique is done by plastic surgeons across the world, who perform mega liposuction (removing more than 10L of fat in one session). This has a disastrous effect on the body’s metabolism and increases the risk of Pulmonary Fat embolism. However, when liposuction is done using tumescent local anaesthesia (lignocaine), it is found to be safe. This concept was invented by Dr Jefferey Klein, California, USA in the 1980s. IN this technique, a dilute solution of local anaesthesia is infiltrated into the fat compartment making it numb. Fat is then removed using thin steel tubes called microcannulae (less than 3.5mm diameter). Dr Klein has shown that the combination of using Tumescent Local Anaesthesia and Microcannulae gives the best results in liposuction. Dermatologist across the world have continued to use this technique giving superb results and at the same time not endangering lives. But plastic surgeons refuse to accept this concept and hence, deaths continue to be a major risk factor of liposuction done under general anaesthesia.",
    para5:"One big advantage of liposuction is acquiring good quality fat that can be used for regeneration purposes. Adipose tissue has lots of mesenchymal stem cells (MSCs) that are only found in Bone marrow. Fat can be easily removed from under the skin and then used as appropriate. There is an abundance of it and hence there is never a shortage. When placed on fat, it helps in giving huge boost to facial structure and texture of overlying skin. This is called a Fat Grafting. It helps in enhancing the individual own features. The skin gets a wonderful change in texture and color which often is termed as baby skin. There is no increase in size of face as is often feared by patients. You can see it for yourself in the pictures of fat grafting posted in Gallery section of website.",
    para6:"SO visit Juvenis Clinic and  ask Dr Goyal to examine you and discuss whether you are a good candidate for lipobodysculpting. ",
    para7:"Just FYI, Dr Nilesh Goyal is the only dermatosurgeon from India to be trained in Liposuction and Fat grafting by Dr Jefferey Klein who is the inventor of Tumescent Anaesthesia Liposuction. He has been performing these procedures for the last 16 years. He is now a board member of the International Society for ",
  
    para8:"Dr Nilesh Goyal is a certified trainer in liposuction and fat grafting. He has got students from India, Bangladesh and the Middle East. Together with his students, he has formed an organization called ",
    para8half:"that aims to spread awareness amongst dermatologists in India about these procedures.",
    videosrc:"https://www.youtube.com/embed/c4MD8rVTSnk?rel=0",
    images: [
      "/Juvenis-images-compress/Arms-liposuction-3-weeks.jpg",
      "/Juvenis-images-compress/Axillary-fat-pad-Liposuction.jpg",
      "/Juvenis-images-compress/Gynecomastia-Liposuction-3-weeks.jpg",
      "/Juvenis-images-compress/lipo2.jpg",
      "/Juvenis-images-compress/Liposuction abdomen right side view.jpg",
    
      "/Juvenis-images-compress/Liposuction of waist with abdomen.jpg",
      "/Juvenis-images-compress/Lower-back-liposuction-4-ltrs-removed-01.jpg",
      "/Juvenis-images-compress/Male lower abdomen and waist liposuction.jpg",
    ]

   },
   {
    
    slug:"acne-surgery",
    title:"Acne Surgery",
    halftitle:"",
    subtitle:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sed nisl pellentesque, faucibus libero eu, gravida quam.",
    img:"/Surgical-Services/acne-scar-surgery.jpg",
    spantext:"",
    headline:"Acne Surgery",
    para1:"Illum possimus tenetur rerum dolore sit perferendis unde cumque molestias debitis consequuntur est, accusantium sed sequi asperiores necessitatibus recusandae ducimus blanditiis consequatur optio voluptas iste quos aspernatur excepturi. Ad nisi modi recusandae dolor quidem inventore perferendis adipisci totam temporibus, eligendi soluta dolores eveniet neque sit ab corporis! Aliquid laboriosam molestiae dolore optio ab, perspiciatis quos doloribus, atque deserunt harum reiciendis facere amet modi architecto voluptate vitae sunt placeat in fugiat? Eligendi illum quisquam voluptatem quidem ipsam tempore sapiente voluptates dolor autem praesentium iure aspernatur amet temporibus, libero, deserunt ullam minus animi rerum molestias suscipit blanditiis porro deleniti! Fuga sequi quaerat, aspernatur distinctio aliquam deserunt voluptate blanditiis possimus et veritatis repellendus doloribus asperiores animi exercitationem reiciendis culpa saepe illo at.",
    para2:"",
    para3:"Maiores quod sint et ipsa voluptate, saepe fugit quis rem id sed illum. Perferendis doloremque ducimus magni tempora eligendi enim, cupiditate quam quae alias! Eos eum modi itaque corporis aliquid harum, provident, laborum mollitia qui a quasi enim delectus accusamus doloribus vitae odit maiores porro? Expedita praesentium ipsum laborum amet facere ratione? Ut, quia. Accusantium quos dolores reprehenderit molestias, ea dolor nobis, repudiandae nihil voluptate alias nam culpa quia porro maiores cum ullam quam assumenda provident? Magni eos eum incidunt id corporis fugiat quam minus nulla at consectetur! Odit voluptatibus quod iure, cumque excepturi voluptatum? Iure officiis accusantium laboriosam harum quos. Molestiae porro hic qui mollitia aut, cupiditate quis enim. Dolore, quas quod itaque nostrum, sunt natus cumque expedita, pariatur rem incidunt nihil accusamus quis vel ex. Eos, temporibus. Molestias reprehenderit beatae et laudantium blanditiis placeat quasi cupiditate, eos obcaecati! Officiis deserunt, sequi ipsam sint doloremque rem odio nulla quis illo sit ut.",
    para4:"",
    para5:"",
    para6:"",
    para7:"",
    para7:"",

   },
   
   {
    
    slug:"anti-aging",
    title:"Anti Aging",
    halftitle:"",
    subtitle:"Juvenis clinic offers anti aging treatments. These should rather be considered as longevity solutions. They aim to increase years of healthy beautiful looking individuals. ",
    img:"/Medical-Services/anti-aging.jpg",
    spantext:"",
    headline:"Anti Aging",
    para1:"Dr Nilesh Goyal has often been commented upon as looking the same by patients who visit after 15-20 years. This ability to maintain looks and physique needs a comprehensive approach to satisfy body’s needs. Human body needs only two things in adequate proportions and at the right time. These are food and sleep.",
    para2:"It is advised that a person should have at least 4 meals per day ie. Breakfast, lunch, evening snack and dinner. Meals should be well balanced with adequate proportions of carbohydrates, fats and proteins with rich sources of vitamins and minerals from salads and fruits. Food Fads often result in nutritional deficiencies which have disastrous effect on skin and hair.",
    para3:"Sleep not later than 10pm for at least 7-8 hours helps a lot in maintaining the hormonal balance and metabolism. It is now found that weight loss can be only achieved when sleep is of good quality and adequate quantity. Sleeping at 10pm or earlier helps in improving digestion of food and absorption of nutrients thus improving overall health. This gives beautiful blemish free skin and free flowing lustrous hair.",
    para4:"Longevity treatments are aimed at improving skin glow and hair quality and quantity. They also aim at overall fitness of body with toned muscles and better bone health. Daily life demands a lot from body taking a toll on its health. This results in production of free oxygen radicals that damage tissues and organs. These can be repaired when we sleep early, take adequate antioxidants that help in countering the damaging effects. These are reservatrol, astaxanthin, co enzyme Q10, glutathione, vitamin c, vitamin e, ginseng, collagen and many newer molecules that are constantly been discovered. These molecules have to be sourced from the right countries to achieve maximum benefit. ",
    para5:"This can be supplemented with treatments that take care of soft wrinkles like Botulinum toxin injections and Filling of skin and subcutaneous space to tackle deep wrinkles. Loss of soft tissue and bony structure happens as part of aging. This can be corrected by Autologous Fat grafting under the skin. This gives the best results and enhances the person’s original features.",
    para6:"Further skin tightening can be achieved with Thread lift and Fractional CO2 laser treatments. These cause a lift of tissues with development of new collagen under the skin.",
    para7:"Ask Dr Goyal what best suits your longevity interests.",
 

   },
   {
    
    slug:"pigmentation-treatment",
    title:"Pigmentation Treatment",
    halftitle:"",
    subtitle:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sed nisl pellentesque, faucibus libero eu, gravida quam.",
    img:"/Medical-Services/pigmentation-treatment.jpg",
    spantext:"",
    headline:"Pigmentation Treatment",
    para1:"Lorem ipsum dolor sit amet consectetur adipisicing elit.Illum possimus tenetur rerum dolore sit perferendis unde cumque molestias debitis consequuntur est, accusantium sed sequi asperiores necessitatibus recusandae ducimus blanditiis consequatur optio voluptas iste quos aspernatur excepturi. Ad nisi modi recusandae dolor quidem inventore perferendis adipisci totam temporibus, eligendi soluta dolores eveniet neque sit ab corporis! Aliquid laboriosam molestiae dolore optio ab, perspiciatis quos doloribus, atque deserunt harum reiciendis facere amet modi architecto voluptate vitae sunt placeat in fugiat? Eligendi illum quisquam voluptatem quidem ipsam tempore sapiente voluptates dolor autem praesentium iure aspernatur amet temporibus, libero, deserunt ullam minus animi rerum molestias suscipit blanditiis porro deleniti! Fuga sequi quaerat, aspernatur distinctio aliquam deserunt voluptate blanditiis possimus et veritatis repellendus doloribus asperiores animi exercitationem reiciendis culpa saepe illo at..",
    para2:"",
    para3:"",
    para4:"",
    para5:"",
    para6:"",
    para7:"",
    para7:"",

   },
   {
    slug:"tread-lift",
    title:"Tread lift",
    subtitle:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sed nisl pellentesque, faucibus libero eu, gravida quam.",
    img:"/Surgical-Services/thread-lift.jpg",
    halftitle:"",
    spantext:"",
    headline:"Tread Lift",
    para1:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio accusamus consequatur rerum aut expedita, sapiente illum ipsum similique ratione dolore maiores perferendis quo vitae commodi iusto molestiae magni reiciendis fugit dicta deleniti praesentium ea magnam minima? Eius suscipit fuga nobis assumenda! Voluptas nesciunt unde vel.",
    para2:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio accusamus consequatur rerum aut expedita, sapiente illum ipsum similique ratione dolore maiores perferendis quo vitae commodi iusto molestiae magni reiciendis fugit dicta deleniti praesentium ea magnam minima? Eius suscipit fuga nobis assumenda! Voluptas nesciunt unde vel.",
    para3:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio accusamus consequatur rerum aut expedita, sapiente illum ipsum similique ratione dolore maiores perferendis quo vitae commodi iusto molestiae magni reiciendis fugit dicta deleniti praesentium ea magnam minima? Eius suscipit fuga nobis assumenda! Voluptas nesciunt unde vel.",
    para5:"",
  images: [
      "/Juvenis-images-compress/Thread lift 39 yr old.jpg",
      "/Juvenis-images-compress/Thread lift 42 yr old.jpg",
      "/Juvenis-images-compress/Thread lift 46 yr old.jpg",
      "/Juvenis-images-compress/Thread lift and fat filling of face 61 yr old.jpg",
      "/Juvenis-images-compress/Thread lift cheeks and jowls 63 yr old on MTx .jpg",
     
    ]

   },
   {
    slug:"scar-revision",
    title:"Scar Revision",
    subtitle:"Scars are a bane for those who have them. They want to get rid of them or at least make them less visible at any cost. Progress in science and technology has been a big boon for such people.",
     img:"/Surgical-Services/acne-scar-surgery.jpg",
    halftitle:"",
    spantext:"",
    headline:"Scar Revision",
    link:"Fat grafting.",
    para1:"Scars are a bane for those who have them. They want to get rid of them or at least make them less visible at any cost. Progress in science and technology has been a big boon for such people.",
    para2:"Often scars can be corrected by surgery where in they are cut out and replaced with better looking scar by doing a cosmetic suturing. This is a very specialized work that comes with years spent in mastering the techniques of suturing. These can be further helped with Fractional CO2 laser treatments during surgery and after stitch removal. These help in growth of collagen within the scar to make it firmer and stronger.",
    para3:"Raised or thickened scars tend to be often painful or itchy and ugly looking. These are classified as Keloids or Hypertrophic scars. They can be treated by preventing the multiplication of fibroblasts ( healing cell that lays down fibrin). Dr Goyal has invented a combination of 3 drugs that can be injected into these scars to help them flatten. (link to the page on Triple combination injection). This treatment is very well accepted by most dermatologists in india and abroad. Again modification of scar can be done once it has flattened with Fractional CO2 laser treatments.",
    para5:"A depressed scar will need lifting. This can be achieved using synthetically prepared Hyaluronic acid injections (commonly called as dermal fillers). They can also be lifted by placing fat underneath the scar. Fat has far greater advantage over fillers which are inert material. Fat helps significantly in improving the color and texture of scar. It also makes the scar supple. Of particular importance are burn or operative scars on scalp. Such scars need a couple of fat grafting sessions following which hair transplant results are significantly better. Many times nanofat injections into scars helps them with stem cell regeneration. ",
    para6:"Dr Nilesh Goyal is an expert in",
    para6half:"He has done many cases in the last 10 years and has also taught many dermatologist from world over.",
    para7:"One does not have to live with scars anymore. Just call 9769966696 to seek a consultation with Dr Goyal to improve your scar.",
    images: [
      
    ]
   },{
    slug:"Alopecia-Areata",
    title:"Alopecia Areata",
    subtitle:"You might have heard of the term alopecia. This means hair loss. However, a type of alopecia called alopecia areata means patchy hair loss with no specific pattern. This is an autoimmune disease that has become a malady for many patients.",
    img:"/Medical-Services/Alopecia-Areata.jpg",
    halftitle:"",
    spantext:"",
    headline:"Alopecia Areata",
    spanheadline:"A malady for many",
    para1:"You might have heard of the term alopecia. This means hair loss. However, a type of alopecia called alopecia areata means patchy hair loss with no specific pattern. This is an autoimmune disease that has become a malady for many patients.",
    para2:"Alopecia areata used to be a single or few areas of hair loss that would recover in most cases on its own. The patches would often by found during haircut by barbers/ salon therapists who are good at this. The disease is thought to be due to a change in immune system resulting in an attack on the hair follicles preventing them from growing out of the scalp/ skin. The patch looks clean area with no hair follicle, sometimes showing faint green black dots on surface as a reminder of the follicles underneath.",
    para3:"Regrowth happens when the disease process is reversed. This can happen on its own or with medications that change the immune status. In the recent years this disease is taking on a very stubborn course with recurrence every time the medications are reduced or withdrawn. This causes extreme agony to patients as often it is difficult to hide the bald patches with remaining hair. this gets more difficult when the disease affects facial hairs like beard, moustache and eyebrows.",
    para4:"Medical treatments include application of creams and oral medications only when the disease is extensive and rapidly spreading, Injections are given into the patches if there are few in number. It is not advisable to go for injections of steroids in case of large patch that has positive pull test at periphery. Also in case of multiple patches (more than 3) often the disease is spreading and would not get treated with injections alone",
    para5:"When the disease is extensive and spreading, then oral immunosuppressives like steroids and other drugs have to be administered. Often these are needed for prolonged periods. They have side effects. The dermatologist looks into the pros and cons of each immunosuppressive pertaining  to each case and decides the best one.",
    para6:"As the cause of this change in immune system that gives rise to alopecia areata is not known, it is found that a period of stress is common in all patients. Hence it is very important for achieving successful treatment, that there is change to healthy lifestyle. Better lifestyle habits have to be adopted. Of primary importance is the habit of sleeping early at 10pm to sync with nature. This helps in maintaining  normal metabolism and hormonal rhythm. Eating food at right times will again ensure proper digestion and nutrient absorption. These help in maintaining better immune health.",
    para7:"Dr Nilesh Goyal is of the firm opinion that a steady decline in responsiveness in alopecia areata with frequent recurrences is due to the massive change in lifestyle brought about by our 24/7 available digital world.",
    para8:"The biggest stress to the human body is the persistent habit of eating and sleeping at odd hours. This has a long-term deleterious effect on immune functioning resulting in autoimmune and allergic diseases and even cancer.",
    images: [
      
    ]
   }
]