export const ServicesData=[
  {
    slug:"hairfall",
    title:"Hairfall and its remedy",
    subtitle:"We diagnose the root cause of hair fall and offer customized treatments to restore healthy hair growth",
    img:"/service-banners/hairfall.jpg",
    spantext:"It Starts",
    headline:"Hairfall and its remedy",
    para1:"Today hairfall is the most common issue affecting all ages right from ages of 5years till old age. Every one has different reasons for their hairfall which usually starts as a sudden onset and can linger on for many months and years leading to significant loss of volume of hair and tinning on top of head.",
    para2:"The most common reason for hairfall tends to be lifestyle induced stress. This stress can be physical due to long hectic hours of work or study, arising from late nights and lack of good quality sleep. To add to this, are poor eating habits like avoiding certain nutritious foods or eating at wrong times which can make one deficient in essential micronutrients required for good hair growth. Late nights cause an upset of digestive systems that cause poor absorption of nutrients from our diet, despite eating a “healthy nutritious” diet. Coupled with physical stress, is the mental stress that takes its toll on sleep and mood. This also restricts many normal physiological processes that affect our haircycle length leading to excess hairfall.",
    para3:"To add to the stress of hairfall is the presence of dandruff that makes the scalp very greasy and hair dry and frizzy. Managing such hair tresses is very difficult and frustrating. Dandruff is sign of weakness of immune system that starts to fail under the effect of stress. This dandruff is an overgrowth of fungus, Pityrosporum ovale, which is present on the scalp of every human being and is supposed to protect us from other more infectious bacteria and fungi.",
    para4:"Juvenis Clinic specializes in identifying the root cause of hairfall for each patient and tailor make treatments that will stop hairfall within 2 months and then regrow hair within the next 4 months. Emphasis is laid more on lifestyle modifications as they will help a lot in treatment outcomes. A mix of oral medications (antifungals, hair vitamins, etc) and applications that help in stopping hairfall and grow hair are given along with the right kind of shampoo and conditioner for the hair type.",
    para5:"Dr Nilesh Goyal also specializes in Nanofat/ SVF injections for hair regrowth. This is modified fat that is rich in stem cells and growth factors that helps in regrowing hair in most types of alopecia. This is proven to be far superior to PRP which has only growth factors.",
    para6:"Genetic cause of alopecia results in patterned hair loss in males and females. This is caused by the effect of DiHydroTestosterone (DHT) on the hair cycle length and its diameter. This eventually causes roots to disappear leading to balding. This requires treatments that cut off the effect of DHT on hair roots and in some cases hair transplant surgery to fill the gaps. Juvenis clinic follows the latest technique for HT surgery ie. FUE (Follicular Unit Extraction) method of acquiring grafts and implantation with two forceps method. (link to page on hair transplant surgery)"

   } ,
   {
    slug:"Psoriasis",
    title:"Psoriasis Treatment",
    subtitle:"We diagnose the root cause of hair fall and offer customized treatments to restore healthy hair growth",
    img:"/service-banners/psoriasis.jpg",
    spantext:"It Starts",
    headline:"psoriasis Treatment",
    para1:"Psoriasis is an inflammatory skin condition affecting upto 2% of the worlds population. It has a strong association with stress and hence, is associated with many systemic lifestyle illnesses like diabetes, hypertension and heart disease.",
    para2:"It has been proven to be a genetic disease. So, in essence, patients of psoriasis have a gene that leads to start of the disease. It is difficult to predict the time of onset. It has been found to occur in infancy and can also present first time at the far end of life. The association with stressful lifestyle is very strong. There has been a slow increase in psoriasis in India over the last few decades. This could be due to increasing unhealthy lifestyle choices by persons all age groups.",
    para3:"Due to its genetic causation, it is impossible to cure one of psoriasis. However, huge research by pharma companies in the western world has now got us multiple highly effective treatment options that can make a person disease free.",
    para4:"Current treatment modalities include cream applications, oral tablets and injectable biologics that have together helped in achieving near 100% PASI reduction. Treatemtn intensity is directly proportional to disease severity and patient health. Also some of the latest drugs are very expensive which leads to cost benefit evaluation while deciding treatment plan.",
    para5:"Dr Nilesh Goyal has worked in many skin centres across the NHS UK where he has managed many psoriasis patients of all ages and with severe forms of disease. He has been part of Psoriasis clinic at Hope Hospital, Manchester UK which caters to the most severely affected by psoriasis.",
    para6:"Come to Juvenis Clinic to get your psoriasis managed as per international standards with latest medications. Treatment plans are tailored to suit your lifestyle and budgets.",
   } ,
   {
    slug:"filler",
    title:"",
    subtitle:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sed nisl pellentesque, faucibus libero eu, gravida quam.",
    img:"/service-banners/filler.jpg",
    halftitle:"Filler in city for an antiaging effect",
    spantext:"Fat the best",
    headline:"Fat the best filler in city for an antiaging effect",
    para1:"Fat as a Filler? Shocking and even disgusting to some. Putting fat into your face suddenly brings in images of bloated face and an immediate NO!! from my patients. But when they see the results of others who have undergone this same procedure, they immediately agree to get it done.",
    para2:"The idea of fat as a filler originated about 130 years ago when modern day fillers were not invented. It was primarily thought of as a volume restoring agent filled under scars of tuberculosis which was rampant in Germany at the time. Many other agents were also tried at the time including animal fat and paraffin wax but all these led to tragic outcomes. An individuals own fat worked and survived the best when inserted under depressed areas. But then the acquiring of fat became an issue as fat had to be cut out from some other area of body resulting in a new scar. The procedure fell into disrepute till Liposuction got invented in the mid 1970s in Europe. Liposuction gave access to a huge quantity of fat which was usually thrown away after the procedure. But Prof Pierre Fournier, an aesthetic surgeon from Paris, realized that this fat could be injected on the face to restore volume. He would also go to the lengths of asking patients to rub the fat into their face every night to get a glow. Long after, the advancement in medical science revealed the superior quality of fat as a grafting material. It was found to have an abundance of Mesenchymal Stem Cells now called as Adipose Derived Stem Cells (ADSCs). Along with these messiahs of repair, are a whole host of growth factors which help in regenerating tissues where this fat is placed.",
    para3:"Fat grafting is a surgical procedure that needs sterile instruments and a clean sterile operating theatre. Patient must be healthy with well controlled parameters of blood sugar and blood pressure. The filling of fat is ideally measured with injection of saline to calculate the exact amount in each segment of face. There is no set formula for filling as it is done for hyaluronic acid (HA) fillers done commonly in dermatology clinics across the world. This helps in enhancing the features specific to the person. It contrasts with the clone like appearance of all those who get HA fillers done.",
    para5:"The art of fat filling is like a sculptor working on a stone statue and giving it the perfect shape step by step. The guidance is not to overfill as fat cells would not survive if there were too many in a small area. It is generally understood that around half of the injected fat gets resorbed by the body. But the remaining half survives for life giving a filling effect. The stem cells and growth factors also placed along with adipocytes help in regenerating the aging tissues and fresh texture to skin. The glow thus acquired is unmatchable with any known current skin rejuvenating technology like Lasers/ RF tightening/ microneedling/ PRP or stem cells injections. This glow lasts for years compared with that from all the other procedures.",
   },
   {
    slug:"Hairtransplant",
    title:"Your Journey to",
    halftitle:"Starts Here.",
    subtitle:"We offer safe and effective hair transplant solutions to help you regain hair density and boost your confidence.",
    img:"/service-banners/hair-transplant.jpg",
    spantext:"Fuller Hair",
    headline:"Hair Transplant Surgery",
    para1:"Hair transplant surgery is a vital cog in the correction of hair thinning and loss of volume. It was envisaged in the 1950s and 60s when the concept of male pattern hair loss was identified by Norman Orentriech. The idea that hair follicles continue to retain their characteristics even when they are transplanted to a different area is the basis for hair transplant surgery.",
    para2:"The procedure has undergone many changes since its invention. From strips of scalp being placed in the recipient areas to now single follicular unit grafts, it has changed dramatically giving near natural appearance to patients world over. The change in techniques with modern instruments have led to faster and more quicker surgeries with larger areas covered in one sitting.",
    para3:"Juvenis Clinic follows the latest in Hair transplant Surgery techniques. It specializes in doctor led Follicular Unit Extraction (FUE) and two forceps implantation technique that is the norm over the last 15 years. The procedure is done by Dr Nilesh Goyal who was trained in this surgery by Dr Robert Jones of Toronto, Canada. He has a team of well trained HT Technicians and Nurses who assist in the procedure. All members of the team have their role defined leading to a smooth flow throughout the procedure.",
    para4:"FUE technique has taken away the pain and bleeding that used to be the norm with strip method of hair transplants. Apart from a mild heaviness of the head, there is no pain after the procedure. A small strip of tight bandage is placed on forehead to prevent swelling of eyes after the surgery. Patient comfort is given utmost importance during the entire procedure which can last upto 12 hours. Dr Nilesh Goyal specializes in giving scalp nerve blocks that reduce the sensations over the entire scalp. Dr Jeffrey Klein’s (California, USA) technique of Tumescent Local Anaesthesia is employed for the donor and recipient areas. This makes the procedure very safe and comfortable for patients.",
    para5:"A detailed post procedure instruction sheet is given to patients who are taught the technique of washing grafted area without touching them. A regime of antibiotics and hair growth stimulants are to be followed to get the desired results.",
    para6:"The grafts get settled in the new location within 2 weeks and then start to grow in 2 months after the surgery. Complete growth takes around 6 to 8 months. Patients are called twice tin the first month after surgery and then are seen 2 monthly to check on their progress.",
    para7:"Current market trends are such that patients are lured to hair transplant clinics with the promise of very cheap rates. Do not fall prey to such gimmicks. These clinics are not manned by proper doctors and to top it, the procedure is done by technicians only whose training and level of expertise cannot be ascertained. The doctors at such clinics are not trained in hair transplant surgeries. There are also many studios that offer hair transplant surgery. Beware of these as there is no doctor in these places.",
    para7:"Dr Goyal has corrected many failed hair transplant surgeries done at such dubious centres.",

   },
   {
    slug:"vitiligo-treatment",
    title:"Vitiligo Treatment",
    halftitle:"",
    subtitle:"Vitiligo, also known as the dreaded White patch disease, Leukoderma or Kode in local language, is an autoimmune disease that can occur at any age and in all human beings across the globe. It does not spare even famous celebrities",
    img:"/service-banners/Vitiligo-Treatment-banner.jpg",
    spantext:"Start Here",
    headline:"Vitiligo Treatment",
    para1:"Vitiligo, also known as the dreaded White patch disease, Leukoderma or Kode in local language, is an autoimmune disease that can occur at any age and in all human beings across the globe. It does not spare even famous celebrities. Michael Jackson was afflicted by it for which he depigmented himself completely when a large part of his skin turned white. ",
    para2:"In india, the white patches are mistaken for Leprosy which is a bacterial infection of the skin causing lighter patches with no sensations. There is a huge social stigma attached to leprosy as it is a communicable disease resulting in severe deformities of hands and feet. With modern day access to treatment, deformities in leprosy have reduced significantly. However, the social stigma refuses to die down. ",
    para3:"Vitiligo presents as a depigmented white patch on any part of the body. It has no preceding symptoms of redness or itching. It spreads slowly with increasing size of patches and occasionally newer ones coming at sites of injury. exacerbations of disease can be often be times with other serious illnesses and periods of stress.",
    para4:"Vitiligo can also occur only in one half of the body when it is called segmental vitiligo. This variant spreads rapidly and then stops after a few months. It is difficult to treat this with medications only but it responds very well to surgical methods.The other variant is Lip Tip variety. Here patches are present on lips and tips of fingers. These areas show very poor response to medications which are used mainly for stabilizing the disease. Stable vitiligo is that which has shown new patches or extension of old patches for a period of 6 months at least",
    para5:"The common variant is the Non Segmental vitiligo that presents with patches in any part of the body and spreads slowly. It responds well to medications, however, these must be continued for long to achieve complete repigmentation. In some patients, the disease keeps recurring despite treatment.",
    para6:"",
    para7:"",
    para7:"",

   },
    {
    slug:"acne-treatment",
    title:"Acne Treatment",
    halftitle:"",
    subtitle:"Acne commonly known as pimples or zits are common in teenage years but can often present into late twenties or early thirties when they become a huge nuisance.",
    img:"/service-banners/acne-scar-treatment.jpg",
    spantext:"",
    headline:"Acne Treatment",
    para1:"The common presentations are that of red bumps which turn into yellow heads (pustules) that rupture leaving raw areas on face. In severe cases, there can be deep seated nodules that heal with scars. Scars remain for life though they often get better as time passes. To treat acne early is to prevent scars that are permanent.",
    para2:"Treatment of acne depends upon the stage and age of patient. Early in the disease, treatments are mainly geared towards killing the bacteria responsible for infection of the enlarged sebaceous glands in the skin. Later, there are treatments that improve function of sebaceous glands by unblocking them and regulating sebum production. Isotretinoin is the only drug that works on this pathway and hence makes a big difference in the outcome. But a full course of isotretinoin lasting few months can leave a person with dry lips, nose, eyes and skin. The benefits of such treatment far outweigh the side effects. An oily complexion in hot humid summers of Mumbai will start loving their skin when on isotretinoin.",
    para3:"Isotretinoin does have scar modifying effect too on acne scars. They look much reduced when the course is on. But after finishing the course these scars return to normal skin colour. Such scars can be treated with modern dermatosurgical methods like Subcision using Nokor needle, Fractional co2 laser resurfacing, Fat grafting including nanofat injections, scar excision, punch excision, etc. In extreme scarring full skin dermabrasion has been done by Dr Goyal with very good cosmetic results. (Link to pics)",
    para4:"Adult Acne needs a mention here. These are acne that occur after the age of 25 years. The primary characteristic of such acne is that they present as red pimples that stay for very long, do not convert to yellow head and often heal with a pigmented scar. They are always secondary to hormonal upset because of stressful  lifestyle measures.",
    para5:"",
    para6:"",
    para7:"",
    para7:"",

   },
   {
    
    slug:"vitiligo-surgery",
    title:"Vitiligo Surgery",
    halftitle:"",
    subtitle:"Vitiligo, also known as the dreaded White patch disease, Leukoderma or Kode in local language, is an autoimmune disease that can occur at any age and in all human beings across the globe. It does not spare even famous celebrities",
    img:"/service-banners/Vitiligo-Treatment-banner.jpg",
    spantext:"Start Here",
    headline:"Vitiligo Surgery",
    para1:"India is at the forefront of vitiligo surgery with conceptualizing the ideas and showing them to work in various types of vitiligo. There are more than 5 types of vitiligo surgery that are routinely done to achieve repigmentation. These are Non cultured Epidermal Cell Suspension done by putting a mixture of epidermal cells (most superficial layer of skin) onto the white patches. Then there is Jodhpur technique which uses a mixture of epidermal cells by dermabrading the skin surrounding the patches or from a different site and places them onto the white patches. Follicular Unit Hair Grafting into the patches is also a very successful type of surgery for repigmentation. Dr Nilesh Goyal specializes in transplanting pubic hair onto the vitiligo patch and achieving repigmentation. The older surgical methods like suction blister grafting, ultra-thin skin grafting and mini punch grafting are also done in specific situations. ",
    para2:"In india, the white patches are mistaken for Leprosy which is a bacterial infection of the skin causing lighter patches with no sensations. There is a huge social stigma attached to leprosy as it is a communicable disease resulting in severe deformities of hands and feet. With modern day access to treatment, deformities in leprosy have reduced significantly. However, the social stigma refuses to die down. ",
    para3:"Vitiligo presents as a depigmented white patch on any part of the body. It has no preceding symptoms of redness or itching. It spreads slowly with increasing size of patches and occasionally newer ones coming at sites of injury. exacerbations of disease can be often be times with other serious illnesses and periods of stress.",
    para4:"Vitiligo can also occur only in one half of the body when it is called segmental vitiligo. This variant spreads rapidly and then stops after a few months. It is difficult to treat this with medications only but it responds very well to surgical methods.The other variant is Lip Tip variety. Here patches are present on lips and tips of fingers. These areas show very poor response to medications which are used mainly for stabilizing the disease. Stable vitiligo is that which has shown new patches or extension of old patches for a period of 6 months at least",
    para5:"The common variant is the Non Segmental vitiligo that presents with patches in any part of the body and spreads slowly. It responds well to medications, however, these must be continued for long to achieve complete repigmentation. In some patients, the disease keeps recurring despite treatment.",
    para6:"",
    para7:"",
    para7:"",

   },
   {
    
    slug:"eczema",
    title:"Eczema",
    halftitle:"",
    subtitle:"Eczema is a broad term encompassing various forms of skin conditions that has become red, itchy and can ooze.",
    img:"/service-banners/Eczema.jpg",
    spantext:"",
    headline:"Eczema",
    para1:"Atopic Dermatitis: Often hereditary, this is the most common form of eczema. It typically presents as itchy, inflamed skin and is frequently associated with asthma or hay fever. Presents often in Infancy and can have a tumultuous progression throughout life. This tends to have an effect on the physical growth of child and their educational performance. Treatments can include immunosuppressant medications like Steroids, Cyclosporine, Azathioprine and latest biological drugs. ",
    para2:"Contact Dermatitis: Caused by skin's reaction to irritants or allergens, this type leads to localized redness and inflammation where the substance came into contact.",
    para3:"Dyshidrotic Eczema(aka Pompholyx): This form affects the hands and feet, causing small, itchy blisters. It’s often triggered by stress, allergens, or exposure to certain metals.",
    para4:"Nummular Eczema: This variety manifests as coin-shaped patches of irritated skin, commonly caused by dry skin or environmental changes.",
    para5:"Seborrheic Dermatitis: Often linked to oil-producing areas like the scalp and face, this form leads to flaky patches and redness. It starts due to overgrowth of a fungus, Malassezia species on scalp which is the result of poor immune response secondary to stressful lifestyle.",
    para6:"Stasis Dermatitis: (aka Gravitational eczema) Related to poor circulation in the lower legs, it can cause swollen, itchy skin and discoloration around ankles progressing upwards when not treated. Often this can lead to cellulitis needing hospital admission for IV antibiotics.",
    para7:"",
    para7:"",

   },
   {
    
    slug:"Liposuction",
    title:"Liposuction",
    halftitle:"",
    subtitle:"Eczema is a broad term encompassing various forms of skin conditions that has become red, itchy and can ooze.",
    img:"/service-banners/Liposuction-or-Body-Sculpting-banner.jpg",
    spantext:"",
    headline:"Liposuction",
    para1:"Atopic Dermatitis: Often hereditary, this is the most common form of eczema. It typically presents as itchy, inflamed skin and is frequently associated with asthma or hay fever. Presents often in Infancy and can have a tumultuous progression throughout life. This tends to have an effect on the physical growth of child and their educational performance. Treatments can include immunosuppressant medications like Steroids, Cyclosporine, Azathioprine and latest biological drugs. ",
    para2:"Contact Dermatitis: Caused by skin's reaction to irritants or allergens, this type leads to localized redness and inflammation where the substance came into contact.",
    para3:"Dyshidrotic Eczema(aka Pompholyx): This form affects the hands and feet, causing small, itchy blisters. It’s often triggered by stress, allergens, or exposure to certain metals.",
    para4:"Nummular Eczema: This variety manifests as coin-shaped patches of irritated skin, commonly caused by dry skin or environmental changes.",
    para5:"Seborrheic Dermatitis: Often linked to oil-producing areas like the scalp and face, this form leads to flaky patches and redness. It starts due to overgrowth of a fungus, Malassezia species on scalp which is the result of poor immune response secondary to stressful lifestyle.",
    para6:"Stasis Dermatitis: (aka Gravitational eczema) Related to poor circulation in the lower legs, it can cause swollen, itchy skin and discoloration around ankles progressing upwards when not treated. Often this can lead to cellulitis needing hospital admission for IV antibiotics.",
    para7:"",
    para7:"",

   },
   {
    
    slug:"acne-surgery",
    title:"Acne Surgery",
    halftitle:"",
    subtitle:"Acne commonly known as pimples or zits are common in teenage years but can often present into late twenties or early thirties when they become a huge nuisance.",
    img:"/service-banners/Acne-Scar-Surgery.jpg",
    spantext:"",
    headline:"Acne Surgery",
    para1:"The common presentations are that of red bumps which turn into yellow heads (pustules) that rupture leaving raw areas on face. In severe cases, there can be deep seated nodules that heal with scars. Scars remain for life though they often get better as time passes. To treat acne early is to prevent scars that are permanent.",
    para2:"Treatment of acne depends upon the stage and age of patient. Early in the disease, treatments are mainly geared towards killing the bacteria responsible for infection of the enlarged sebaceous glands in the skin. Later, there are treatments that improve function of sebaceous glands by unblocking them and regulating sebum production. Isotretinoin is the only drug that works on this pathway and hence makes a big difference in the outcome. But a full course of isotretinoin lasting few months can leave a person with dry lips, nose, eyes and skin. The benefits of such treatment far outweigh the side effects. An oily complexion in hot humid summers of Mumbai will start loving their skin when on isotretinoin.",
    para3:"Isotretinoin does have scar modifying effect too on acne scars. They look much reduced when the course is on. But after finishing the course these scars return to normal skin colour. Such scars can be treated with modern dermatosurgical methods like Subcision using Nokor needle, Fractional co2 laser resurfacing, Fat grafting including nanofat injections, scar excision, punch excision, etc. In extreme scarring full skin dermabrasion has been done by Dr Goyal with very good cosmetic results. (Link to pics)",
    para4:"Adult Acne needs a mention here. These are acne that occur after the age of 25 years. The primary characteristic of such acne is that they present as red pimples that stay for very long, do not convert to yellow head and often heal with a pigmented scar. They are always secondary to hormonal upset because of stressful lifestyle measures.",
    para5:"",
    para6:"",
    para7:"",
    para7:"",

   },
   {
    
    slug:"anti-aging",
    title:"Anti Aging",
    halftitle:"",
    subtitle:"The common presentations are that of red bumps which turn into yellow heads (pustules) that rupture leaving raw areas on face. In severe cases, there can be deep seated nodules that heal with scars. Scars remain for life though",
    img:"/service-banners/anti-aging.jpg",
    spantext:"",
    headline:"Anti Aging",
    para1:"The common presentations are that of red bumps which turn into yellow heads (pustules) that rupture leaving raw areas on face. In severe cases, there can be deep seated nodules that heal with scars. Scars remain for life though they often get better as time passes. To treat acne early is to prevent scars that are permanent.",
    para2:"Treatment of acne depends upon the stage and age of patient. Early in the disease, treatments are mainly geared towards killing the bacteria responsible for infection of the enlarged sebaceous glands in the skin. Later, there are treatments that improve function of sebaceous glands by unblocking them and regulating sebum production. Isotretinoin is the only drug that works on this pathway and hence makes a big difference in the outcome. But a full course of isotretinoin lasting few months can leave a person with dry lips, nose, eyes and skin. The benefits of such treatment far outweigh the side effects. An oily complexion in hot humid summers of Mumbai will start loving their skin when on isotretinoin.",
    para3:"Isotretinoin does have scar modifying effect too on acne scars. They look much reduced when the course is on. But after finishing the course these scars return to normal skin colour. Such scars can be treated with modern dermatosurgical methods like Subcision using Nokor needle, Fractional co2 laser resurfacing, Fat grafting including nanofat injections, scar excision, punch excision, etc. In extreme scarring full skin dermabrasion has been done by Dr Goyal with very good cosmetic results. (Link to pics)",
    para4:"Adult Acne needs a mention here. These are acne that occur after the age of 25 years. The primary characteristic of such acne is that they present as red pimples that stay for very long, do not convert to yellow head and often heal with a pigmented scar. They are always secondary to hormonal upset because of stressful lifestyle measures.",
    para5:"",
    para6:"",
    para7:"",
    para7:"",

   },
   {
    
    slug:"pigmentation-treatment",
    title:"Pigmentation Treatment",
    halftitle:"",
    subtitle:"Pigmentation Treatment",
    img:"/service-banners/pigmentation-treatment.jpg",
    spantext:"",
    headline:"Pigmentation Treatment",
    para1:"The common presentations are that of red bumps which turn into yellow heads (pustules) that rupture leaving raw areas on face. In severe cases, there can be deep seated nodules that heal with scars. Scars remain for life though they often get better as time passes. To treat acne early is to prevent scars that are permanent.",
    para2:"Treatment of acne depends upon the stage and age of patient. Early in the disease, treatments are mainly geared towards killing the bacteria responsible for infection of the enlarged sebaceous glands in the skin. Later, there are treatments that improve function of sebaceous glands by unblocking them and regulating sebum production. Isotretinoin is the only drug that works on this pathway and hence makes a big difference in the outcome. But a full course of isotretinoin lasting few months can leave a person with dry lips, nose, eyes and skin. The benefits of such treatment far outweigh the side effects. An oily complexion in hot humid summers of Mumbai will start loving their skin when on isotretinoin.",
    para3:"Isotretinoin does have scar modifying effect too on acne scars. They look much reduced when the course is on. But after finishing the course these scars return to normal skin colour. Such scars can be treated with modern dermatosurgical methods like Subcision using Nokor needle, Fractional co2 laser resurfacing, Fat grafting including nanofat injections, scar excision, punch excision, etc. In extreme scarring full skin dermabrasion has been done by Dr Goyal with very good cosmetic results. (Link to pics)",
    para4:"Adult Acne needs a mention here. These are acne that occur after the age of 25 years. The primary characteristic of such acne is that they present as red pimples that stay for very long, do not convert to yellow head and often heal with a pigmented scar. They are always secondary to hormonal upset because of stressful lifestyle measures.",
    para5:"",
    para6:"",
    para7:"",
    para7:"",

   },
   
]